#! /bin/bash

cd "$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
cd ..

BLUE='\033[0;34m'
NC='\033[0m'

echo -e "... 1/2 🐍 installing ${BLUE}pipenv${NC}\n"
pip install pipenv

echo -e "\n... 2/2 🔧 installing ${BLUE}dependencies${NC} (this might take a while)\n"
pipenv install
