#! /bin/bash

cd "$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

GREEN='\033[0;32m'
BOLD='\033[0;1m'
NC='\033[0m'

echo -e "➡️ ${BOLD}Setuping ${GREEN}robot${NC}...\n"
../robot/scripts/setup

echo -e "\n\n➡️ ${BOLD}Setuping ${GREEN}backend${NC}...\n"
../backend/scripts/setup

echo -e "\n\n➡️ ${BOLD}Setuping ${GREEN}frontend${NC}...\n"
cd ../frontend && yarn
