name: Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '!frontend/README.md'

jobs:
  lint:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./frontend

    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Installing yarn
        run: sudo apt install yarn

      - name: Installing dependencies
        run: yarn
        working-directory: ${{env.working-directory}}

      - name: Linting
        run: yarn lint
        working-directory: ${{env.working-directory}}
