name: Robot

on:
  push:
    paths:
      - 'robot/**'
      - '!robot/README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      python-version: 3.8
    defaults:
      run:
        working-directory: ./robot

    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Setuping Python ${{ env.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.python-version }}
      
      - name: Caching dependencies
        uses: actions/cache@v1
        with:
          path: '~/.cache/pip'
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Installing dependencies
        run: pip install -r requirements.txt
        
      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
      - name: Testing
        run: python -m nose2

      - name: Code coverage
        run: |
          python -m coverage run
          python -m coverage report
